#!/usr/bin/env python3
# PUBLISH-GATE-SELF-EXCLUDE
#
# This file is exempt from the denylist scan, and it says so where a reviewer
# will see it. Reason: it is a *stripping tool*. Its job is to find and remove
# the overclaim "institutional-grade" and the third-party font host
# fonts.googleapis.com, so both strings necessarily appear here as regex
# sources. A tool that searches for a banned string cannot avoid containing it.
# The exemption covers this file only; the exclusion is printed by the gate on
# every run, so it can never hide silently.
"""apply_holding.py — put every published report page into the HOLDING state.

Idempotent. Run from anywhere:

    python3 tools/apply_holding.py            # apply to all <TICKER>/index.html
    python3 tools/apply_holding.py --check    # report only, change nothing

For each report page it:
  1. inserts a fixed "UNDER RE-VERIFICATION" banner immediately after <body>,
     styled with the report template's own CSS custom properties;
  1b. injects a <style> block that reserves the banner's height at the top of
     the page (--holding-banner-h) and pushes the report's own fixed chrome
     (.site-header, .sidebar) down by it, so the banner never covers the
     report header;
  2. adds <meta name="robots" content="noindex,nofollow"> to <head>;
  3. removes every <link> to a third-party font host (fonts.googleapis.com /
     fonts.gstatic.com), including rel=preconnect hints, so the page makes no
     external requests;
  4. replaces the phrase "institutional-grade" (any case) with "experimental".

The site root index.html is NOT touched — it is hand-authored for this release.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

BANNER_ID = "holding-banner"

BANNER = (
    '<div id="' + BANNER_ID + '" role="alert" style="position:fixed;top:0;left:0;right:0;'
    "z-index:2147483647;box-sizing:border-box;padding:9px 16px;"
    "background:var(--bg-card,#1a2234);color:var(--text-primary,#e8edf5);"
    "border-bottom:2px solid var(--accent-yellow,#eab308);"
    "font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif;"
    'font-size:13px;line-height:1.5;text-align:center;">'
    '<strong style="color:var(--accent-yellow,#eab308);letter-spacing:0.06em;">'
    "UNDER RE-VERIFICATION</strong> &mdash; generated by an experimental pipeline; "
    "factual errors were found in a related batch (Aug 2026). Not investment advice. "
    '<a href="../" style="color:var(--accent-gold,#C9A227);text-decoration:underline;">'
    "See the homepage.</a></div>"
)

STYLE_ID = "holding-banner-style"

# Height reserved for the banner, as one CSS custom property.
#   desktop: 9px padding-top + 9px padding-bottom + 13px * 1.5 line-height
#            + 2px border-bottom  =  39.5px  -> 40px
# Narrower viewports wrap the banner text, so the reservation grows with it:
#   <=768px : two lines  -> 18 + 39 + 2  = 59px  -> 62px (2px slack)
#   <=480px : three/four lines -> 18 + 58.5 + 2 = 78.5px -> 84px
BANNER_H = "40px"
BANNER_H_TABLET = "62px"
BANNER_H_PHONE = "84px"

# The report template puts .site-header at `position:fixed; top:0` and anchors
# .sidebar / .main-content on --header-height. A fixed banner therefore sits ON
# TOP of the header unless both are shifted; body padding alone is not enough
# for fixed elements. This block is injected LAST in <head> so it wins on
# source order without needing !important.
STYLE = (
    '<style id="' + STYLE_ID + '">'
    ":root{--holding-banner-h:" + BANNER_H + "}"
    "@media (max-width:768px){:root{--holding-banner-h:" + BANNER_H_TABLET + "}}"
    "@media (max-width:480px){:root{--holding-banner-h:" + BANNER_H_PHONE + "}}"
    "body{padding-top:var(--holding-banner-h)}"
    ".site-header{top:var(--holding-banner-h)}"
    ".sidebar{top:calc(var(--header-height,90px) + var(--holding-banner-h))}"
    ".section{scroll-margin-top:calc(100px + var(--holding-banner-h))}"
    "</style>"
)

ROBOTS = '<meta name="robots" content="noindex,nofollow">'

# <link ...fonts.googleapis.com...> / <link ...fonts.gstatic.com...>, incl. preconnect hints.
FONT_LINK_RE = re.compile(
    r"[ \t]*<link\b[^>]*fonts\.(?:googleapis|gstatic)\.com[^>]*>[ \t]*\r?\n?",
    re.IGNORECASE,
)
BODY_RE = re.compile(r"<body\b[^>]*>", re.IGNORECASE)
HEAD_RE = re.compile(r"<head\b[^>]*>", re.IGNORECASE)
# Anchor the robots meta after <meta charset> so the charset declaration stays first.
CHARSET_RE = re.compile(r"<meta\b[^>]*charset=[^>]*>", re.IGNORECASE)
BANNER_RE = re.compile(r'<div id="' + BANNER_ID + r'".*?</div>\s*', re.IGNORECASE | re.DOTALL)
STYLE_RE = re.compile(r'<style id="' + STYLE_ID + r'".*?</style>\s*', re.IGNORECASE | re.DOTALL)
HEAD_CLOSE_RE = re.compile(r"</head>", re.IGNORECASE)
ROBOTS_RE = re.compile(r'<meta\b[^>]*name=["\']robots["\'][^>]*>', re.IGNORECASE)
INSTITUTIONAL_RE = re.compile(r"institutional[-‑– ]grade", re.IGNORECASE)


def report_pages() -> list[Path]:
    """Every <TICKER>/index.html at the repo root (uppercase dir name)."""
    out = []
    for d in sorted(REPO.iterdir()):
        if not d.is_dir() or d.name.startswith("."):
            continue
        if d.name != d.name.upper() or not d.name.isalpha():
            continue
        page = d / "index.html"
        if page.is_file():
            out.append(page)
    return out


def transform(html: str) -> tuple[str, dict[str, int]]:
    counts = {"font_links": 0, "robots": 0, "banner": 0, "style": 0,
              "institutional": 0}

    html, counts["font_links"] = FONT_LINK_RE.subn("", html)

    if not ROBOTS_RE.search(html):
        m = CHARSET_RE.search(html) or HEAD_RE.search(html)
        if m is None:
            raise ValueError("no <head> element")
        html = html[: m.end()] + "\n" + ROBOTS + html[m.end():]
        counts["robots"] = 1

    # Re-insert the offset stylesheet from scratch (same idempotency rule as the
    # banner: strip any previous copy first, so a re-run never stacks two).
    stripped = STYLE_RE.sub("", html)
    if stripped == html:
        counts["style"] = 1
    else:
        html = stripped
    m = HEAD_CLOSE_RE.search(html)
    if m is None:
        raise ValueError("no </head> element")
    html = html[: m.start()] + STYLE + "\n" + html[m.start():]

    # Re-insert the banner from scratch so edits to BANNER propagate on re-run.
    m = BODY_RE.search(html)
    if m is None:
        raise ValueError("no <body> element")
    rest = html[m.end():]
    stripped = BANNER_RE.sub("", rest, count=1)
    if stripped != rest:
        rest = stripped
    else:
        counts["banner"] = 1
    html = html[: m.end()] + "\n" + BANNER + "\n" + rest.lstrip("\n")

    html, counts["institutional"] = INSTITUTIONAL_RE.subn("experimental", html)
    return html, counts


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="do not write; report what would change")
    args = ap.parse_args()

    pages = report_pages()
    if not pages:
        print("no report pages found under", REPO, file=sys.stderr)
        return 1

    changed = 0
    for page in pages:
        original = page.read_text(encoding="utf-8")
        new, counts = transform(original)
        state = "same" if new == original else ("would change" if args.check else "written")
        if new != original:
            changed += 1
            if not args.check:
                page.write_text(new, encoding="utf-8")
        print(
            f"{page.relative_to(REPO)!s:<22} {state:<13} "
            f"font_links_removed={counts['font_links']} robots_added={counts['robots']} "
            f"banner_added={counts['banner']} offset_style_added={counts['style']} "
            f"institutional_grade_replaced={counts['institutional']}"
        )

    print(f"\n{len(pages)} report page(s); {changed} changed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
